# Generated by Django 3.0.3 on 2020-11-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('execute_curve_matching', 'Execute Curve Matching'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
